// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import Doorloop from 'doorloop';

export const metadata: Metadata = {
  resource: 'lease_credits',
  operation: 'write',
  tags: [],
};

export const tool: Tool = {
  name: 'create_lease_credits',
  description: 'Creates a Lease Credit',
  inputSchema: {
    type: 'object',
    properties: {
      date: {
        type: 'string',
        description: 'Format: YYYY-MM-DD',
      },
      lease: {
        type: 'string',
        title: 'mongoId',
      },
      lines: {
        type: 'array',
        items: {
          type: 'object',
          title: 'leaseTransactionLine',
          properties: {
            account: {
              type: 'string',
              description: 'References the Account Id for this line.',
            },
            amount: {
              type: 'number',
            },
            id: {
              type: 'string',
              title: 'mongoId',
            },
            balance: {
              type: 'string',
              description: 'Read Only.',
            },
            memo: {
              type: 'string',
            },
          },
          required: ['account', 'amount'],
        },
      },
      batch: {
        type: 'string',
      },
      memo: {
        type: 'string',
      },
      reference: {
        type: 'string',
        description: 'If not provided one will be generated by the server',
      },
    },
  },
};

export const handler = (client: Doorloop, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return client.leaseCredits.create(body);
};

export default { metadata, tool, handler };
