// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'doorloop-mcp/filtering';
import { Metadata, asTextContentResult } from 'doorloop-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Doorloop from 'doorloop';

export const metadata: Metadata = {
  resource: 'lease_credits',
  operation: 'write',
  tags: [],
  httpMethod: 'put',
  httpPath: '/lease-credits/{leaseCreditId}',
  operationId: 'put-lease-credit',
};

export const tool: Tool = {
  name: 'update_lease_credits',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nUpdates a Lease Credit\n\n# Response Schema\n```json\n{\n  type: 'object',\n  title: 'journalEntry',\n  properties: {\n    date: {\n      type: 'string',\n      description: 'Format: YYYY-MM-DD'\n    },\n    lease: {\n      type: 'string',\n      title: 'mongoId'\n    },\n    lines: {\n      type: 'array',\n      items: {\n        type: 'object',\n        title: 'leaseTransactionLine',\n        properties: {\n          account: {\n            type: 'string',\n            description: 'References the Account Id for this line.'\n          },\n          amount: {\n            type: 'number'\n          },\n          id: {\n            type: 'string',\n            title: 'mongoId'\n          },\n          balance: {\n            type: 'string',\n            description: 'Read Only.'\n          },\n          memo: {\n            type: 'string'\n          }\n        },\n        required: [          'account',\n          'amount'\n        ]\n      }\n    },\n    batch: {\n      type: 'string'\n    },\n    memo: {\n      type: 'string'\n    },\n    reference: {\n      type: 'string',\n      description: 'If not provided one will be generated by the server'\n    }\n  },\n  required: [    'date',\n    'lease',\n    'lines'\n  ]\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      leaseCreditId: {
        type: 'string',
      },
      date: {
        type: 'string',
        description: 'Format: YYYY-MM-DD',
      },
      lease: {
        type: 'string',
        title: 'mongoId',
      },
      lines: {
        type: 'array',
        items: {
          type: 'object',
          title: 'leaseTransactionLine',
          properties: {
            account: {
              type: 'string',
              description: 'References the Account Id for this line.',
            },
            amount: {
              type: 'number',
            },
            id: {
              type: 'string',
              title: 'mongoId',
            },
            balance: {
              type: 'string',
              description: 'Read Only.',
            },
            memo: {
              type: 'string',
            },
          },
          required: ['account', 'amount'],
        },
      },
      batch: {
        type: 'string',
      },
      memo: {
        type: 'string',
      },
      reference: {
        type: 'string',
        description: 'If not provided one will be generated by the server',
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: ['leaseCreditId', 'date', 'lease', 'lines'],
  },
  annotations: {
    idempotentHint: true,
  },
};

export const handler = async (client: Doorloop, args: Record<string, unknown> | undefined) => {
  const { leaseCreditId, ...body } = args as any;
  return asTextContentResult(await maybeFilter(args, await client.leaseCredits.update(leaseCreditId, body)));
};

export default { metadata, tool, handler };
