// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import Doorloop from 'doorloop';

export const metadata: Metadata = {
  resource: 'vendor_credits',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/vendor-credits',
  operationId: 'post-vendor-credit',
};

export const tool: Tool = {
  name: 'create_vendor_credits',
  description: 'Creates a Vendor Credit',
  inputSchema: {
    type: 'object',
    properties: {
      date: {
        type: 'string',
        description: 'Format: YYYY-MM-DD',
      },
      dueDate: {
        type: 'string',
        description: 'Format: YYYY-MM-DD',
      },
      lines: {
        type: 'array',
        items: {
          type: 'object',
          title: 'expenseTransactionLine',
          properties: {
            account: {
              type: 'string',
              title: 'mongoId',
            },
            linkedToResourceId: {
              type: 'string',
              description: 'The Property Id for this line.',
            },
            linkedToResourceType: {
              type: 'string',
              description: 'At the monent, only "property" is supported',
              enum: ['property'],
            },
            id: {
              type: 'string',
              title: 'mongoId',
            },
            amount: {
              type: 'number',
            },
            balance: {
              type: 'number',
              description: 'Read Only',
            },
            memo: {
              type: 'string',
            },
          },
          required: ['account', 'linkedToResourceId', 'linkedToResourceType'],
        },
      },
      vendor: {
        type: 'string',
        title: 'mongoId',
      },
      id: {
        type: 'string',
        title: 'mongoId',
      },
      batch: {
        type: 'string',
      },
      memo: {
        type: 'string',
      },
      reference: {
        type: 'string',
        description: 'If not provided wil be generated by the server.',
      },
      totalAmount: {
        type: 'number',
        description: 'Read Only. Calculated by the server.',
      },
      totalBalance: {
        type: 'number',
        description: 'Read Only. Calculated by the server.',
      },
    },
  },
};

export const handler = (client: Doorloop, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return client.vendorCredits.create(body);
};

export default { metadata, tool, handler };
