// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'doorloop-mcp/filtering';
import { Metadata, asTextContentResult } from 'doorloop-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Doorloop from 'doorloop';

export const metadata: Metadata = {
  resource: 'lease_reversed_payments',
  operation: 'read',
  tags: [],
  httpMethod: 'get',
  httpPath: '/lease-reversed-payments/{leaseReversedPaymentId}',
  operationId: 'get-lease-reversed-payment',
};

export const tool: Tool = {
  name: 'retrieve_lease_reversed_payments',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nRetrieves a Lease Returned Payment\n\n# Response Schema\n```json\n{\n  type: 'object',\n  properties: {\n    date: {\n      type: 'string',\n      description: 'Format: YYYY-MM-DD'\n    },\n    lease: {\n      type: 'string',\n      title: 'mongoId'\n    },\n    leasePayment: {\n      type: 'string',\n      description: 'Referenced the original Lease Payment Id that was returned'\n    },\n    lines: {\n      type: 'array',\n      items: {\n        type: 'object',\n        title: 'leaseTransactionLine',\n        properties: {\n          account: {\n            type: 'string',\n            description: 'References the Account Id for this line.'\n          },\n          amount: {\n            type: 'number'\n          },\n          id: {\n            type: 'string',\n            title: 'mongoId'\n          },\n          balance: {\n            type: 'string',\n            description: 'Read Only.'\n          },\n          memo: {\n            type: 'string'\n          }\n        },\n        required: [          'account',\n          'amount'\n        ]\n      }\n    },\n    batch: {\n      type: 'string'\n    },\n    memo: {\n      type: 'string'\n    },\n    reference: {\n      type: 'string',\n      description: 'If not provided one will be generated by the server'\n    }\n  },\n  required: [    'date',\n    'lease',\n    'leasePayment',\n    'lines'\n  ]\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      leaseReversedPaymentId: {
        type: 'string',
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: ['leaseReversedPaymentId'],
  },
};

export const handler = async (client: Doorloop, args: Record<string, unknown> | undefined) => {
  const { leaseReversedPaymentId, ...body } = args as any;
  return asTextContentResult(
    await maybeFilter(args, await client.leaseReversedPayments.retrieve(leaseReversedPaymentId)),
  );
};

export default { metadata, tool, handler };
